version: "latest"
services:
  jenkins:
    build: <path>\jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client:ro
    networks:
      - jenkins1
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
    stdin_open: true
    tty: true
    
  nexus:
    build: <path>\nexus
    volumes:
      - nexus:/opt/sonatype/sonatype-work/nexus3
    networks:
      - jenkins1
    ports:
      - 8081:8081
    depends_on:
      - jenkins
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
    stdin_open: true
    tty: true 
    
  stage:
    build: <path>\stage
    networks:
      - jenkins1
    depends_on:
      - jenkins
      - nexus
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    stdin_open: true
    tty: true
    
  appserver:
    build: <path>\appserver
    networks:
      - jenkins1
    ports:
      - 9093:9093
    depends_on:
      - jenkins
      - nexus
      - stage
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    stdin_open: true
    tty: true
    
networks:
  jenkins1:
    driver: bridge
volumes:
  jenkins-data:
  jenkins-certs:
  nexus: